import type { ConstantJournalType } from '../../../../flow/context/ConstantsType'

export const CALENDAR_LOAD_BEGIN: ConstantJournalType = 'writersblock.Journal.CALENDAR_LOAD_BEGIN'
export const CALENDAR_LOAD_FAILURE: ConstantJournalType = 'writersblock.Journal.CALENDAR_LOAD_FAILURE'
export const CALENDAR_LOAD_SUCCESS: ConstantJournalType = 'writersblock.Journal.CALENDAR_LOAD_SUCCESS'

export const CONTENT_ACTION_OPEN: ConstantJournalType = 'writersblock.Journal.CONTENT_ACTION_OPEN'
export const CONTENT_ACTION_CLOSE: ConstantJournalType = 'writersblock.Journal.CONTENT_ACTION_CLOSE'
export const CONTENT_DELETE_BEGIN: ConstantJournalType = 'writersblock.Journal.CONTENT_DELETE_BEGIN'
export const CONTENT_DELETE_FAILURE: ConstantJournalType = 'writersblock.Journal.CONTENT_DELETE_FAILURE'
export const CONTENT_DELETE_SUCCESS: ConstantJournalType = 'writersblock.Journal.CONTENT_DELETE_SUCCESS'
export const CONTENT_LOAD_BEGIN: ConstantJournalType = 'writersblock.Journal.CONTENT_LOAD_BEGIN'
export const CONTENT_LOAD_FAILURE: ConstantJournalType = 'writersblock.Journal.CONTENT_LOAD_FAILURE'
export const CONTENT_LOAD_SUCCESS: ConstantJournalType = 'writersblock.Journal.CONTENT_LOAD_SUCCESS'
export const CONTENT_PATCH_BEGIN: ConstantJournalType = 'writersblock.Journal.CONTENT_PATCH_BEGIN'
export const CONTENT_PATCH_FAILURE: ConstantJournalType = 'writersblock.Journal.CONTENT_PATCH_FAILURE'
export const CONTENT_PATCH_SUCCESS: ConstantJournalType = 'writersblock.Journal.CONTENT_PATCH_SUCCESS'
export const CONTENT_POST_BEGIN: ConstantJournalType = 'writersblock.Journal.CONTENT_POST_BEGIN'
export const CONTENT_POST_FAILURE: ConstantJournalType = 'writersblock.Journal.CONTENT_POST_FAILURE'
export const CONTENT_POST_SUCCESS: ConstantJournalType = 'writersblock.Journal.CONTENT_POST_SUCCESS'

export const CONTENT_TITLE_DELETE_BEGIN: ConstantJournalType = 'writersblock.Journal.CONTENT_TITLE_DELETE_BEGIN'
export const CONTENT_TITLE_DELETE_FAILURE: ConstantJournalType = 'writersblock.Journal.CONTENT_TITLE_DELETE_FAILURE'
export const CONTENT_TITLE_DELETE_SUCCESS: ConstantJournalType = 'writersblock.Journal.CONTENT_TITLE_DELETE_SUCCESS'
export const CONTENT_TITLE_PATCH_BEGIN: ConstantJournalType = 'writersblock.Journal.CONTENT_TITLE_PATCH_BEGIN'
export const CONTENT_TITLE_PATCH_FAILURE: ConstantJournalType = 'writersblock.Journal.CONTENT_TITLE_PATCH_FAILURE'
export const CONTENT_TITLE_PATCH_SUCCESS: ConstantJournalType = 'writersblock.Journal.CONTENT_TITLE_PATCH_SUCCESS'

export const NOTES_ACTION_CLOSE: ConstantJournalType = 'writersblock.Journal.NOTES_ACTION_CLOSE'
export const NOTES_ACTION_OPEN: ConstantJournalType = 'writersblock.Journal.NOTES_ACTION_OPEN'
export const NOTES_LOAD_BEGIN: ConstantJournalType = 'writersblock.Journal.NOTES_LOAD_BEGIN'
export const NOTES_LOAD_FAILURE: ConstantJournalType = 'writersblock.Journal.NOTES_LOAD_FAILURE'
export const NOTES_LOAD_SUCCESS: ConstantJournalType = 'writersblock.Journal.NOTES_LOAD_SUCCESS'
export const NOTES_PATCH_BEGIN: ConstantJournalType = 'writersblock.Journal.NOTES_PATCH_BEGIN'
export const NOTES_PATCH_FAILURE: ConstantJournalType = 'writersblock.Journal.NOTES_PATCH_FAILURE'
export const NOTES_PATCH_SUCCESS: ConstantJournalType = 'writersblock.Journal.NOTES_PATCH_SUCCESS'

export const POST_IT_ACTION_CLOSE: ConstantJournalType = 'writersblock.Journal.POST_IT_ACTION_CLOSE'
export const POST_IT_ACTION_OPEN: ConstantJournalType = 'writersblock.Journal.POST_IT_ACTION_OPEN'
export const POST_IT_DELETE_BEGIN: ConstantJournalType = 'writersblock.Journal.POST_IT_DELETE_BEGIN'
export const POST_IT_DELETE_FAILURE: ConstantJournalType = 'writersblock.Journal.POST_IT_DELETE_FAILURE'
export const POST_IT_DELETE_SUCCESS: ConstantJournalType = 'writersblock.Journal.POST_IT_DELETE_SUCCESS'
export const POST_IT_LOAD_BEGIN: ConstantJournalType = 'writersblock.Journal.POST_IT_LOAD_BEGIN'
export const POST_IT_LOAD_FAILURE: ConstantJournalType = 'writersblock.Journal.POST_IT_LOAD_FAILURE'
export const POST_IT_LOAD_SUCCESS: ConstantJournalType = 'writersblock.Journal.POST_IT_LOAD_SUCCESS'
export const POST_IT_PATCH_BEGIN: ConstantJournalType = 'writersblock.Journal.POST_IT_PATCH_BEGIN'
export const POST_IT_PATCH_FAILURE: ConstantJournalType = 'writersblock.Journal.POST_IT_PATCH_FAILURE'
export const POST_IT_PATCH_SUCCESS: ConstantJournalType = 'writersblock.Journal.POST_IT_PATCH_SUCCESS'
export const POST_IT_POST_BEGIN: ConstantJournalType = 'writersblock.Journal.POST_IT_POST_BEGIN'
export const POST_IT_POST_FAILURE: ConstantJournalType = 'writersblock.Journal.POST_IT_POST_FAILURE'
export const POST_IT_POST_SUCCESS: ConstantJournalType = 'writersblock.Journal.POST_IT_POST_SUCCESS'

export const WYSIWYG_SET_VISIBILITY: ConstantJournalType = 'writersblock.Journal.WYSIWYG_SET_VISIBILITY'