export type ConstantLandingType = 'writersblock.Landing.APP_INITIAL_LOAD'
                                    | 'writersblock.Landing.USER_SETTINGS_DISPLAY'
                                    | 'writersblock.Landing.USER_SETTINGS_CONCEAL'

export type ConstantUserType = 'writersblock.User.USER_LOGIN'
                                    | 'writersblock.User.USER_LOGOUT'
                                    | 'USER_SETTING_APPLY_CHANGES'

export type ConstantJournalType = 'writersblock.Journal.CALENDAR_LOAD_BEGIN'
                                    | 'writersblock.Journal.CALENDAR_LOAD_FAILURE'
                                    | 'writersblock.Journal.CALENDAR_LOAD_SUCCESS'

                                    | 'writersblock.Journal.CONTENT_ACTION_OPEN'
                                    | 'writersblock.Journal.CONTENT_ACTION_CLOSE'
                                    | 'writersblock.Journal.CONTENT_DELETE_BEGIN'
                                    | 'writersblock.Journal.CONTENT_DELETE_FAILURE'
                                    | 'writersblock.Journal.CONTENT_DELETE_SUCCESS'
                                    | 'writersblock.Journal.CONTENT_LOAD_BEGIN'
                                    | 'writersblock.Journal.CONTENT_LOAD_FAILURE'
                                    | 'writersblock.Journal.CONTENT_LOAD_SUCCESS'
                                    | 'writersblock.Journal.CONTENT_PATCH_BEGIN'
                                    | 'writersblock.Journal.CONTENT_PATCH_FAILURE'
                                    | 'writersblock.Journal.CONTENT_PATCH_SUCCESS'
                                    | 'writersblock.Journal.CONTENT_POST_BEGIN'
                                    | 'writersblock.Journal.CONTENT_POST_FAILURE'
                                    | 'writersblock.Journal.CONTENT_POST_SUCCESS'
                                    | 'writersblock.Journal.CONTENT_TITLE_DELETE_BEGIN' // Title content can load with Journal content
                                    | 'writersblock.Journal.CONTENT_TITLE_DELETE_FAILURE'
                                    | 'writersblock.Journal.CONTENT_TITLE_DELETE_SUCCESS'
                                    | 'writersblock.Journal.CONTENT_TITLE_PATCH_BEGIN'
                                    | 'writersblock.Journal.CONTENT_TITLE_PATCH_FAILURE'
                                    | 'writersblock.Journal.CONTENT_TITLE_PATCH_SUCCESS'

                                        // NOTES: have only one. Can only Load and Patch
                                    | 'writersblock.Journal.NOTES_ACTION_CLOSE'
                                    | 'writersblock.Journal.NOTES_ACTION_OPEN'
                                    | 'writersblock.Journal.NOTES_LOAD_BEGIN'
                                    | 'writersblock.Journal.NOTES_LOAD_FAILURE'
                                    | 'writersblock.Journal.NOTES_LOAD_SUCCESS'
                                    | 'writersblock.Journal.NOTES_PATCH_BEGIN'
                                    | 'writersblock.Journal.NOTES_PATCH_FAILURE'
                                    | 'writersblock.Journal.NOTES_PATCH_SUCCESS'

                                    | 'writersblock.Journal.POST_IT_ACTION_CLOSE'
                                    | 'writersblock.Journal.POST_IT_ACTION_OPEN'
                                    | 'writersblock.Journal.POST_IT_DELETE_BEGIN'
                                    | 'writersblock.Journal.POST_IT_DELETE_FAILURE'
                                    | 'writersblock.Journal.POST_IT_DELETE_SUCCESS'
                                    | 'writersblock.Journal.POST_IT_LOAD_BEGIN'
                                    | 'writersblock.Journal.POST_IT_LOAD_FAILURE'
                                    | 'writersblock.Journal.POST_IT_LOAD_SUCCESS'
                                    | 'writersblock.Journal.POST_IT_PATCH_BEGIN'
                                    | 'writersblock.Journal.POST_IT_PATCH_FAILURE'
                                    | 'writersblock.Journal.POST_IT_PATCH_SUCCESS'
                                    | 'writersblock.Journal.POST_IT_POST_BEGIN'
                                    | 'writersblock.Journal.POST_IT_POST_FAILURE'
                                    | 'writersblock.Journal.POST_IT_POST_SUCCESS'

                                    | 'writersblock.Journal.WYSIWYG_SET_VISIBILITY'
